version: '3'

services:
  reverse-proxy:
    image: nginx:1.17.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - fhir

  fhir:
    image: arkhn/fhir-api:latest
    ports:
      - 8081:8081
