version: '3'

services:
  reverse-proxy:
    image: nginx:1.17.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - fhir

  fhir:
    build:
      context: ./fhir-api
    image: arkhn/fhir-api:latest
    container_name: fhir-api
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
    volumes:
      - ./fhir-api:/srv/flask_app
    ports:
      - 8081:8081
      - 5000:5000

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: fhirstore
    ports:
      - 27017:27017
    volumes:
      - fhirstore-db:/data/db

volumes:
  fhirstore-db:
