version: '3'

services:
  reverse-proxy:
    image: nginx:1.17.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - fhir

  fhir:
    build:
      context: ./fhir-api
    environment:
      FLASK_DEBUG: 1
    volumes:
      - ./fhir-api:/srv/flask_app
    ports:
      - 8081:8081
      - 5000:5000

  fhirbase:
    image: fhirbase/fhirbase:latest
    ports:
      - 5432:5432
      - 3000:3000
