version: "3.7"

services:
  reverse-proxy:
    image: nginx:1.17.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - fhir
    networks:
      - arkhn

  fhir:
    build:
      context: ./fhir-api
    image: arkhn/fhir-api:latest
    container_name: fhir-api
    env_file:
      - fhir-api/.env.docker
    volumes:
      - ./fhir-api:/srv/flask_app
    ports:
      - 2000:2000
    networks:
      - arkhn

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: arkhn
      MONGO_INITDB_DATABASE: fhirstore
      MONGO_INITDB_ROOT_PASSWORD: SuperSecurePassword2019
    ports:
      - 27017:27017
    volumes:
      - fhirstore-db:/data/db
    command: --replSet rs0
    networks:
      - arkhn

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    container_name: elasticsearch
    environment:
      ELASTIC_PASSWORD: SuperSecurePassword2019
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data
    networks:
      - arkhn

  monstache:
    image: rwynn/monstache:6.2.5
    container_name: monstache
    command: -f /opt/monstache.toml
    restart: always
    volumes:
      - ./monstache.toml:/opt/monstache.toml
    depends_on:
      - mongo
      - elasticsearch
    networks:
      - arkhn

volumes:
  fhirstore-db:
  esdata:
    driver: local

networks:
  arkhn:
    name: arkhn_network
