export const TOKEN_STORAGE_KEY = 'ARKHN_AUTH_TOKEN';
export const {
  REACT_APP_FHIR_API_URL: FHIR_API_URL,
  REACT_APP_AUTH_API_URL: AUTH_API_URL,
} = process.env;

export const HISTORY_SEARCH_SIZE = 100;
