name: fhir-api

on: push

jobs:
  lint:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          pip install flake8
      - run: |
          flake8 fhir-api --config=fhir-api/.flake8 --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 fhir-api --config=fhir-api/.flake8 --count --max-complexity=10 --max-line-length=100 --statistics

  build:
    needs: lint
    runs-on: ubuntu-18.04

    steps:
      - id: metadata
        run: |
          IMAGE=arkhn/fhir-api
          VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          TAGS="${IMAGE}:${VERSION},${IMAGE}:${GITHUB_SHA::8}"
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #      - run: |
      #          docker build fhir-api -f fhir-api/Dockerfile -t ${{ steps.metadata.outputs.tag }} -t ${{ steps.metadata.outputs.registry }}/${{ github.repository }}/fhir-api:${{ steps.metadata.outputs.version }}
      #          docker push docker.pkg.github.com/${{ github.repository }}/fhir-api:${{ steps.metadata.outputs.version }}

      - uses: docker/build-push-action@v2
        with:
          context: fhir-api
          file: ./fhir-api/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: |
            com.arkhn.image.title=fhir-api
            com.arkhn.image.description=${{ github.event.repository.description }}
            com.arkhn.image.url=${{ github.event.repository.html_url }}
            com.arkhn.image.source=${{ github.event.repository.clone_url }}
            com.arkhn.image.version=${{ steps.metadata.outputs.version }}
            com.arkhn.image.created=${{ steps.metadata.outputs.created }}
            com.arkhn.image.revision=${{ github.sha }}
            com.arkhn.image.licenses=${{ github.event.repository.license.spdx_id }}

#      - name: Test with pytest
#        run: |
#          cd fhir-api
#          python -m pytest -svv tests/

#  publish:
#    name: Build and publish
#    env:
#      GITHUB_REGISTRY: docker.pkg.github.com
#      IMAGE: arkhn/fhir-api
#      TAG: latest
#    runs-on: ubuntu-18.04
#    needs: build
#    if: github.ref == 'refs/heads/master'
#    steps:
#        run: docker build -t $IMAGE:$TAG -f fhir-api/Dockerfile fhir-api/
#      - name: Publish to the docker hub
#        run: |
#          echo "${{ secrets.DOCKER_PASSWORD }}" |  docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
#          docker push $IMAGE:$TAG
#      - name: Publish to Github Packages
#        run: |
#          echo "${{ secrets.GITHUB_TOKEN }}" | docker login $GITHUB_REGISTRY -u ${{ github.actor }} --password-stdin
#          docker tag $IMAGE:$TAG $GITHUB_REGISTRY/${{ github.repository }}/fhir-api:$TAG
#          docker push $GITHUB_REGISTRY/${{ github.repository }}/fhir-api:$TAG
